name: Build

on:
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@master

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.20.3"

      - name: Update PATH
        run: |
          echo "/opt/hostedtoolcache/protoc/3.20.3/x64/bin" >> $GITHUB_PATH

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
